# Generated by Django 4.0.5 on 2022-06-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('subtitle', models.CharField(max_length=999)),
                ('content', models.TextField()),
                ('url', models.URLField(max_length=999)),
                ('imgUrl', models.URLField(max_length=999)),
                ('bgUrl', models.URLField(max_length=999)),
                ('imgAlt', models.CharField(max_length=999)),
            ],
        ),
    ]
